name: API CI - Continuous Integration

on:
  push:
    branches:
      - test_pipeline
  pull_request:
    branches:
      - dev

jobs:
  lint-and-test:
    name: Lint e Testes
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Config Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install Dependencies
      run: go mod tidy

    - name: Verify Code Lint
      run: go fmt ./...

  build:
    name: App Compiler
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build Binary
        run: go build -p app ./cmd/main.go
      
      - name: Binary Cache
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: ./app
