name: App CD - Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Docker Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t meu-usuario/meu-app:latest .

      - name: Deploy Docker Hub Image
        run: docker push meu-usuario/meu-app:latest

  deploy:
    name: Server Deploy
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Connect and Update Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull meu-usuario/meu-app:latest
            docker stop meu-app || true
            docker rm meu-app || true
            docker run -d --name meu-app -p 8080:8080 meu-usuario/meu-app:latest
